sudo: false
language: node_js
node_js:
- 6
script:
- npm run build
deploy:
  provider: npm
  email: s.j.robinson1@lancaster.ac.uk
  api_key:
    secure: WcZJJVklG/k2sqxJdcJGzydAqBHCEqKW9nMyCAljFkbseLvDjIk85tqGR6hfJdH1sPIH3Ya+dnk/EEWqq+0VssxkSikGiuuInq2pA8gHDg1s8cleWRTWN94XYGDKEzLuOmPBf4qzIlTX6RVRPzlYw/AOxjYF9bbaAudtK1dyWEhAUllyxLUpgW/4TAlONMxTGgbwYAXIdcbMIG+pRAlTEFY6LFvaCjaawtfgwQ6V6KsYTjZ5QX+a2heHEhnbwbpBAHulBz1/OA+RDy19fvNiVSKO3g8MktBA8lXy9BC3whMrpFBoOKeRWJ9ysHiBOOtoZEUfVge61v66ddQ7BUZt2otURpfTFGL5Vb15lR1yBgPd7uqLHPuqt5scM87uD+NUkkaXGxLdch2SZZvNL4amaAYto5baDdliLeJDbwbO/83rRmf/La+G+7K0wz0YOpfkv3aid5EGBbYSrQ2ltKUi2SGZ/OLGXbNeZrkqhAp2HCw3IXh0P07XW17yBnUra1GQYc/uvbFmTaEr5j9OeZZjtS8//+/k6DlpNVh1cZyzb4AGVT/0j1Sd2U7cP3VpGmxJA0pZm/Rlct+/EtEGTDDf+Uw9j1mmzIYaZ7poq+wofjKtaTO3MrBA/W1NCCYjGO4MCOg5Plx4fn4yOFKkSZX7mhHPUloQQ8vQC03Unv6u63g=
  on:
    tags: true
    repo: lulibrary/Vue2Leaflet